Sample sheets

# SAMPLE_SHEET_CFP: data/raw_CFP/WTS1_sample_sheet.csv
raw_CFP: data/raw_CFP/WTS1_sample_sheet.csv
# DATA_DIR_CFP: raw_CFP

# SAMPLE_SHEET_YFP: data/raw_YFP/WTS1_sample_sheet.csv
raw_YFP: data/raw_YFP/WTS1_sample_sheet.csv
# DATA_DIR_YFP: raw_YFP

# SAMPLE_SHEET_normalize_1: data/normalize_1/WTS1_sample_sheet.csv
normalize_1: data/normalize_1/WTS1_sample_sheet.csv
# DATA_DIR_normalize_1: normalize_1

# SAMPLE_SHEET_normalize_2: data/normalize_2/WTS1_sample_sheet.csv
normalize_2: data/normalize_2/WTS1_sample_sheet.csv
# DATA_DIR_normalize_2: normalize_2

# SAMPLE_SHEET_normalize_3: data/normalize_3/WTS1_sample_sheet.csv
normalize_3: data/normalize_3/WTS1_sample_sheet.csv
# DATA_DIR_normalize_3: normalize_3

# SAMPLE_SHEET_normalize_4: data/normalize_4/WTS1_sample_sheet.csv
normalize_4: data/normalize_4/WTS1_sample_sheet.csv
# DATA_DIR_normalize_4: normalize_4

DATA_DIR_n1_28sample: n1_28sample

# WTS2_correlogram_cells
# normalize_1: output/WTS4/normalize_1/PeriodicACF/sample_over5.csv